### ISSUE TITLE
dotfiles 참고 링크 드려용

### ISSUE THREAD

**Issue by koremp** [0stellensatz/dotfiles#1]
https://github.com/johngrib/dotfiles/tree/master/nvim
인스타 친구,,,인데 친해지고 싶엇수,,,

**Comment by koremp** [comment]
왠지 있으면 잘 쓰실 것 같으셔서 (수학과시지만,,)

**Comment by 0stellensatz** [comment]
감사합니다!

**Comment by koremp** [comment]
https://johngrib.github.io/wiki/vim/
저는 이거 보고 참고 많이 했어용 (오지랖,,)
